<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="australia.aspx.cs" Inherits="EXPLORE.subpages.australia" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="header" style="padding: 150px; margin: 0px; background-image: url('/img/australia.jpg'); background-repeat: no-repeat; background-attachment: fixed; font-size: 15vw; height: 500px; letter-spacing: 1vw; text-align: center; color: #FFFFFF; font-family: Calibri; width: auto;">AUSTRALIA</h1>
    <div style="margin-right: 100px; margin-left: 100px; padding: 80px">
        <div>
            
        </div>
        <br />

        <article style="font-weight: bold; font-size: large; color: #0033CC; font-family: Calibri">The continent of Australia, sometimes known in technical contexts by the names Sahul (/səˈhuːl/), Australia-New Guinea, Australinea,[citation needed] Meganesia, or Papualand to distinguish it from the country of Australia, is located within the Southern and Eastern Hemispheres.[1] The name "Sahul" takes its name from the Sahul Shelf, which is part of the continental shelf of the Australian continent. The continent includes mainland Australia, Tasmania, the island of New Guinea (Papua New Guinea and portions of Indonesia), the Aru Islands, the Ashmore and Cartier Islands, most of the Coral Sea Islands, and some other offshore continental islands. Situated in the geographical region of Oceania, Australia is the smallest of the seven traditional continents.</article>
        <p style="text-align: justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin imperdiet finibus lobortis. Cras dignissim varius lacus, non efficitur elit semper non. Aliquam interdum facilisis varius. In dapibus ac est a egestas. Nunc aliquet condimentum nunc non pulvinar. Nulla pretium ultricies eros quis rutrum. Nulla suscipit quam urna, sit amet egestas tortor faucibus et. Praesent non euismod elit. Nam cursus a metus finibus tincidunt. Vestibulum porttitor nunc vitae libero porta pretium. Nunc dignissim ante iaculis, elementum erat ac, tincidunt tortor. Nam pellentesque consectetur quam ut mattis. Aenean hendrerit eros erat, eget sollicitudin ligula suscipit id. Pellentesque luctus eros ac nisi consequat blandit. Suspendisse et erat ipsum. Phasellus sagittis tortor elit, eget pharetra orci scelerisque gravida.

Sed tristique turpis eu tincidunt tempus. Nunc in eros auctor, eleifend nisi non, lobortis metus. In sed nulla molestie erat luctus laoreet. Nam euismod odio id tortor consequat pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras vitae vulputate lacus. Mauris eget nisi vitae velit consequat vulputate.

Morbi vehicula orci sed lorem viverra elementum. Nullam venenatis massa vitae ante convallis gravida sit amet sed eros. Suspendisse elit nisi, lacinia id neque consequat, pharetra convallis sem. Duis accumsan risus et nisi sagittis suscipit. Morbi pulvinar ultricies volutpat. Nam dapibus eros neque, quis ornare est vestibulum in. Pellentesque gravida varius est ut cursus. Aliquam urna est, pulvinar cursus volutpat sed, feugiat vel nibh. Aenean sodales varius egestas. Etiam ultricies lectus metus, vel pharetra orci feugiat id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed tempor justo id aliquam dignissim. Suspendisse ex quam, congue vitae pellentesque ut, lobortis eu sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla lacus lorem, finibus vitae vehicula in, sodales et velit. Etiam sed ornare augue. Vivamus lacinia nulla ut quam ullamcorper, nec laoreet ante venenatis. Fusce ex magna, ullamcorper vel efficitur ac, blandit ultrices lectus. Quisque facilisis est vitae erat molestie, vel luctus tortor ornare. Integer pretium gravida faucibus. Duis vitae orci sed augue luctus tempor ac quis urna. Curabitur laoreet mauris sed metus luctus, ullamcorper blandit justo vulputate. Nullam mattis, turpis a cursus mollis, justo velit dapibus mi, sit amet blandit lorem lacus in enim. Mauris luctus condimentum ex et mollis.

Integer iaculis sem metus, sed lacinia libero pellentesque in. Fusce malesuada tellus velit, malesuada rhoncus lectus fermentum quis. Donec mattis pellentesque enim, a maximus neque aliquam tempus. Fusce sit amet dolor in enim tempor ultrices sit amet quis felis. Etiam odio ex, gravida eget lorem a, convallis ultricies justo. Nulla nec nunc a urna tristique mattis. Sed ac consequat massa, non sollicitudin leo.</p>
        <br />
        <h3>Geographical Information</h3>
        <p>The continent includes a continental shelf overlain by shallow seas which divide it into several landmasses—the Arafura Sea and Torres Strait between mainland Australia and New Guinea, and Bass Strait between mainland Australia and Tasmania. When sea levels were lower during the Pleistocene ice age, including the Last Glacial Maximum about 18,000 BC, they were connected by dry land. During the past 18,000 to 10,000 years, rising sea levels overflowed the lowlands and separated the continent into today's low-lying arid to semi-arid mainland and the two mountainous islands of New Guinea and Tasmania.

With a total land area of 8.56 million square kilometres (3,310,000 sq mi), the Australian continent is the smallest, lowest, flattest, and second-driest continent (after Antarctica) on Earth.[2] As the country of Australia is mostly on a single landmass, and comprises most of the continent, it is sometimes informally referred to as an island continent, surrounded by oceans.[3]

Papua New Guinea, a country within the continent, is one of the most culturally and linguistically diverse countries in the world.[4] It is also one of the most rural, as only 18 percent of its people live in urban centres.[5] West Papua, a province of Indonesia, is home to an estimated 44 uncontacted tribal groups.[6] Australia, the largest landmass in the continent, is highly urbanised,[7] and has the world's 14th-largest economy with the second-highest human development index globally.[8][9] Australia also has the world's 9th largest immigrant population.[10][11]
            <br />
            The Australian continent, being part of the Indo-Australian Plate (more specifically, the Australian Plate), is the lowest, flattest, and oldest landmass on Earth[27] and it has had a relatively stable geological history. New Zealand is not part of the continent of Australia, but of the separate, submerged continent of Zealandia.[28] New Zealand and Australia are both part of the Oceanian sub-region known as Australasia, with New Guinea being in Melanesia.

The continent includes a continental shelf overlain by shallow seas which divide it into several landmasses—the Arafura Sea and Torres Strait between mainland Australia and New Guinea, and Bass Strait between mainland Australia and Tasmania. When sea levels were lower during the Pleistocene ice age, including the Last Glacial Maximum about 18,000 BC, they were connected by dry land. During the past 18,000[29] to 10,000 years, rising sea levels overflowed the lowlands and separated the continent into today's low-lying arid to semi-arid mainland and the two mountainous islands of New Guinea and Tasmania.[30] The continental shelf connecting the islands, half of which is less than 50 metres (160 ft) deep, covers some 2.5 million square kilometres (970,000 sq mi), including the Sahul Shelf[31][32] and Bass Strait.

Geological forces such as tectonic uplift of mountain ranges or clashes between tectonic plates occurred mainly in Australia's early history, when it was still a part of Gondwana. Australia is situated in the middle of the tectonic plate, and therefore currently has no active volcanism.[33]
            Because of its central location on its tectonic plate, Australia doesn't have any active volcanic regions, the only continent with this distinction.[34] The lands were joined with Antarctica as part of the southern supercontinent Gondwana until the plate began to drift north about 96 million years ago. For most of the time since then, Australia–New Guinea remained a continuous landmass. When the last glacial period ended in about 10,000 BC, rising sea levels formed Bass Strait, separating Tasmania from the mainland. Then between about 8,000 and 6,500 BC, the lowlands in the north were flooded by the sea, separating New Guinea, the Aru Islands, and the Australian mainland.

A northern arc consisting of the New Guinea Highlands, the Raja Ampat Islands, and Halmahera was uplifted by the northward migration of Australia and subduction of the Pacific Plate. The Outer Banda Arc was accreted along the northwestern edge the continent; it includes the islands of Timor, Tanimbar, and Seram. Papua New Guinea has several volcanoes, as it is situated along the Pacific Ring of Fire. Volcanic eruptions are not rare, and the area is prone to earthquakes and tsunamis because of this.[35] Mount Wilhelm in Papua New Guinea is the second highest mountain in the continent,[36] and at 4,884 metres (16,024 ft) above sea level, Puncak Jaya is the highest mountain
        </p></div>
</asp:Content>
