<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="placedemo2.aspx.cs" Inherits="EXPLORE.placedemo2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="margin-right: 100px; margin-left: 100px; padding: 80px">
        <h1>Taj Mahal</h1>
        <br />
        <hr />
        <img src="places/Taj/pexels-shalender-kumar-6618044.jpg" style="width: auto; height: 400px" />
        <article style="text-align: justify">
            The Taj Mahal (Persian: تاج محل ; /ˌtɑːdʒ məˈhɑːl, ˌtɑːʒ-/; lit. 'Crown of the Palace', [taːdʒ ˈmɛːɦ(ə)l]),[4][5][6] is an Islamic ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan (r. 1628–1658) to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself. The tomb is the centrepiece of a 17-hectare (42-acre) complex, which includes a mosque and a guest house, and is set in formal gardens bounded on three sides by a crenellated wall.

Construction of the mausoleum was essentially completed in 1643, but work continued on other phases of the project for another 10 years. The Taj Mahal complex is believed to have been completed in its entirety in 1653 at a cost estimated at the time to be around ₹32 million, which in 2020 would be approximately ₹70 billion (about US $1 billion). The construction project employed some 20,000 artisans under the guidance of a board of architects led by the court architect to the emperor, Ustad Ahmad Lahauri. Various types of symbolism have been employed in the Taj to reflect natural beauty and divinity.

The Taj Mahal was designated as a UNESCO World Heritage Site in 1983 for being "the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage". It is regarded by many as the best example of Mughal architecture and a symbol of India's rich history. The Taj Mahal attracts more than 6 million visitors a year[3] and in 2007, it was declared a winner of the New 7 Wonders of the World (2000–2007) initiative.
            </article>
        <br />
        <br />
        <img src="places/Taj/pexels-harivirat-muthyam-9868155.jpg" style="width: auto; height: 400px"/>
        <br />
        <br />
        <p style="text-align: justify">
            Etymology
Abdul Hamid Lahauri, in his book from 1636 Padshahnama, refers to the Taj Mahal as rauza-i munawwara (Perso-Arabic: روضه منواره, rawdah-i munawwarah), meaning the illumined or illustrious tomb.[7] The current name for the Taj Mahal is believed to be derived from the Persian تاج محل tāj mahall, meaning "crown" (tāj) "palace" (mahall).[8][9][4] The name "Taj" came from the corruption of the second syllable of "Mumtaz".[10][11]
            The Taj Mahal was commissioned by Shah Jahan in 1631, to be built in the memory of his wife Mumtaz Mahal, who died on 17 June that year, while giving birth to their 14th child, Gauhara Begum.[12][13] Construction started in 1632,[14] and the mausoleum was completed in 1648, while the surrounding buildings and garden were finished five years later.[15] The imperial court documenting Shah Jahan's grief after the death of Mumtaz Mahal illustrates the love story held as the inspiration for the Taj Mahal.[16]
            The Taj Mahal incorporates and expands on design traditions of Indo-Islamic and earlier Mughal architecture. Specific inspiration came from successful Timurid and Mughal buildings including the Gur-e Amir (the tomb of Timur, progenitor of the Mughal dynasty, in Samarkand),[17] Humayun's Tomb which inspired the Charbagh gardens and hasht-behesht (architecture) plan of the site, Itmad-Ud-Daulah's Tomb (sometimes called the Baby Taj), and Shah Jahan's own Jama Masjid in Delhi. While earlier Mughal buildings were primarily constructed of red sandstone, Shah Jahan promoted the use of white marble inlaid with semi-precious stones. Buildings under his patronage reached new levels of refinement.[18]

Tomb
The tomb is the central focus of the entire complex of the Taj Mahal. It is a large, white marble structure standing on a square plinth and consists of a symmetrical building with an iwan (an arch-shaped doorway) topped by a large dome and finial. Like most Mughal tombs, the basic elements are Indo-Islamic in origin.[19]

The base structure is a large multi-chambered cube with chamfered corners forming an unequal eight-sided structure that is approximately 55 metres (180 ft) on each of the four long sides. Each side of the iwan is framed with a huge pishtaq or vaulted archway with two similarly shaped arched balconies stacked on either side. This motif of stacked pishtaqs is replicated on the chamfered corner areas, making the design completely symmetrical on all sides of the building. Four minarets frame the tomb, one at each corner of the plinth facing the chamfered corners. The main chamber houses the false sarcophagi of Mumtaz Mahal and Shah Jahan; the actual graves are at a lower level.[20]
        </p>
        <br />
        <br />
        <img src="places/Taj/pexels-kritesh-kaushik-2413613.jpg" style="width: auto; height: 400px" />
        <br />
        <br />
        <p style="text-align: justify">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rutrum lacinia ullamcorper. Aliquam vel augue eu nunc iaculis elementum ac a risus. Vestibulum et ullamcorper tortor. Nulla facilisi. Quisque pellentesque lorem ac turpis euismod vestibulum. Nam porttitor varius leo eu viverra. Integer eleifend non arcu sit amet sagittis. In congue sapien lectus, in fringilla nisl gravida eu. Vestibulum in pellentesque diam
            Cras sed massa luctus, posuere turpis et, semper lorem. Pellentesque tempus ipsum et ligula rhoncus, at convallis mauris aliquet. Integer metus lorem, lobortis non ex at, tincidunt tincidunt est. Nullam sit amet consectetur ipsum, quis ullamcorper orci. Donec magna lectus, pretium cursus finibus vel, sollicitudin in mi. Nulla arcu nisi, pharetra eu ullamcorper a, dictum in dolor. Maecenas tortor nulla, fermentum ac lectus ac, imperdiet commodo nisl. Nullam arcu turpis, pretium id lectus ac, rhoncus aliquet augue. In hac habitasse platea dictumst. Sed non dolor non nisi tempus ultrices. Donec eget facilisis erat, non pellentesque odio. Suspendisse eget orci auctor, porttitor est at, aliquam turpis. Curabitur blandit, arcu eu ultrices interdum, ipsum quam consequat sapien, vitae consectetur felis nulla at metus. Suspendisse potenti. Nam bibendum pretium mauris, non ullamcorper leo egestas vitae. Aliquam laoreet dignissim mauris, quis lobortis tortor ullamcorper in.

Fusce sed ex dictum, semper lacus in, ultrices magna. Proin fringilla leo id malesuada scelerisque. Duis pharetra risus nec porta mattis. Phasellus in mi vitae orci lacinia tempor sed nec velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed sollicitudin turpis ut nunc iaculis, eu lacinia odio dictum.

Maecenas et neque id magna pulvinar ornare. Morbi et mattis ipsum. Fusce scelerisque mattis magna, dapibus blandit nulla finibus porttitor. Aliquam eu faucibus libero. Duis erat neque, sodales sit amet faucibus et, pharetra sit amet dolor. Fusce ligula risus, rhoncus ut venenatis vel, condimentum id leo. Cras lobortis neque a neque cursus, ut pellentesque odio volutpat. Nullam facilisis odio vitae ullamcorper mollis. Aenean odio justo, posuere ullamcorper sagittis venenatis, fermentum et tortor. Donec hendrerit justo sed justo semper, nec suscipit ante vulputate. Cras tristique varius ipsum, sit amet blandit magna varius eu. Donec et faucibus quam, id auctor purus. Vivamus lobortis elit id massa viverra aliquet.

Morbi purus arcu, rutrum at tempus nec, finibus vel risus. Duis a posuere eros. Fusce mollis sagittis risus. Integer dignissim pharetra dapibus. Fusce vestibulum metus et viverra malesuada. Donec dui elit, ultrices in egestas at, scelerisque in quam. Aliquam tellus lacus, luctus a lectus sit amet, sagittis condimentum nunc. Fusce vitae placerat nulla. Nam nibh dolor, efficitur quis velit eu, lobortis condimentum erat. Duis lacinia nunc id tincidunt finibus. Suspendisse tempor efficitur urna id rhoncus. Maecenas pulvinar tellus turpis, vel dictum felis vestibulum at. Aenean eu sem libero. Praesent porta nec neque at semper. Phasellus sed pellentesque ipsum. Sed sollicitudin purus orci, ut imperdiet ipsum facilisis at.
            Cras sed massa luctus, posuere turpis et, semper lorem. Pellentesque tempus ipsum et ligula rhoncus, at convallis mauris aliquet. Integer metus lorem, lobortis non ex at, tincidunt tincidunt est. Nullam sit amet consectetur ipsum, quis ullamcorper orci. Donec magna lectus, pretium cursus finibus vel, sollicitudin in mi. Nulla arcu nisi, pharetra eu ullamcorper a, dictum in dolor. Maecenas tortor nulla, fermentum ac lectus ac, imperdiet commodo nisl. Nullam arcu turpis, pretium id lectus ac, rhoncus aliquet augue. In hac habitasse platea dictumst. Sed non dolor non nisi tempus ultrices. Donec eget facilisis erat, non pellentesque odio. Suspendisse eget orci auctor, porttitor est at, aliquam turpis. Curabitur blandit, arcu eu ultrices interdum, ipsum quam consequat sapien, vitae consectetur felis nulla at metus. Suspendisse potenti. Nam bibendum pretium mauris, non ullamcorper leo egestas vitae. Aliquam laoreet dignissim mauris, quis lobortis tortor ullamcorper in.

Fusce sed ex dictum, semper lacus in, ultrices magna. Proin fringilla leo id malesuada scelerisque. Duis pharetra risus nec porta mattis. Phasellus in mi vitae orci lacinia tempor sed nec velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed sollicitudin turpis ut nunc iaculis, eu lacinia odio dictum.

Maecenas et neque id magna pulvinar ornare. Morbi et mattis ipsum. Fusce scelerisque mattis magna, dapibus blandit nulla finibus porttitor. Aliquam eu faucibus libero. Duis erat neque, sodales sit amet faucibus et, pharetra sit amet dolor. Fusce ligula risus, rhoncus ut venenatis vel, condimentum id leo. Cras lobortis neque a neque cursus, ut pellentesque odio volutpat. Nullam facilisis odio vitae ullamcorper mollis. Aenean odio justo, posuere ullamcorper sagittis venenatis, fermentum et tortor. Donec hendrerit justo sed justo semper, nec suscipit ante vulputate. Cras tristique varius ipsum, sit amet blandit magna varius eu. Donec et faucibus quam, id auctor purus. Vivamus lobortis elit id massa viverra aliquet.

Morbi purus arcu, rutrum at tempus nec, finibus vel risus. Duis a posuere eros. Fusce mollis sagittis risus. Integer dignissim pharetra dapibus. Fusce vestibulum metus et viverra malesuada. Donec dui elit, ultrices in egestas at, scelerisque in quam. Aliquam tellus lacus, luctus a lectus sit amet, sagittis condimentum nunc. Fusce vitae placerat nulla. Nam nibh dolor, efficitur quis velit eu, lobortis condimentum erat. Duis lacinia nunc id tincidunt finibus. Suspendisse tempor efficitur urna id rhoncus. Maecenas pulvinar tellus turpis, vel dictum felis vestibulum at. Aenean eu sem libero. Praesent porta nec neque at semper. Phasellus sed pellentesque ipsum. Sed sollicitudin purus orci, ut imperdiet ipsum facilisis at.
        </p>
        <img src="places/Taj/pexels-my-photos-7639064.jpg"style="width: auto; height: 400px" />
    </div>
</asp:Content>
